### ISSUE TITLE
Improve the MSM functionality

### ISSUE THREAD

**Issue by janosg** [covid-19-impact-lab/sid#39]
### What would you like to enhance and why? Is it related to an issue/problem?

The calculation of simulated moments currently always has one of two issues:
1. It is slow (if we use dask)
2. It uses a lot of memory (if we use pandas)

There are several possible solutions

### Solution 1: Only save moments in each period

pros:
- minimal memory requirements
- faster calculation of moments

cons:
- requires large change to existing msm interface
- need to think about a good way of storing the daily moments and aggregating them later on

### Solution 2: Store simulated data more efficiently

There is already a flexible interface that allows to save only the columns we need. If using that properly, most of the required memory is used to save the date column. The most efficient format would just be one `np.uint16` column for a period number. 

Then we could have a function that replaces the date in the empirical data with the correct period number (given start and end period). 

Note that internally, the date would still be available in each period. There is just an option not to have it in the saved dataset. 

pros:
- works better with existing msm interface
- overall fewer changes in code

cons:
- moments are matched by numbers instead of date

### Discussion

I prefer solution 2. @tobiasraabe what do you think?

**Comment by tobiasraabe** [comment]
Solution 2 seems the way to go, although, I'm a little bit surprised that the date column is the issue because the compression algorithm could just replace the dates with integers when the data is stored on the disk. There is so much repetition.

I will profile sid in sid-estimation since some weeks passed until my last time to get a feeling for the required change and then come back.

**Comment by janosg** [comment]
On disk that might be the case. But the goal is to keep it in memory. Then it is less surprising that date takes the most. It's a 64bit dtype and all other columns we keep are categorical or small integers.

**Comment by tobiasraabe** [comment]
#43 implemented an internal sid time and there are other memory usage fixes in #65, #67, and elsewhere. I close this one because it is not specific or relevant anymore.
