### ISSUE TITLE
Remove period everywhere

### ISSUE THREAD

**Issue by janosg** [covid-19-impact-lab/sid#9]
### What would you like to enhance and why? Is it related to an issue/problem?

Work with dates instead of periods everywhere. 

### Describe the solution you'd like

- convert start and end in contact and testing policies to dates, change documentation accordingly
- remove the period column from the states DataFrame (will also save memory)
- raise an error instead of a deprecation warning if period is used anywher
- change the plotting functions?

### Describe alternatives you've considered

We could still keep the period in the states, but I am against it for memory reasons and because they do not add any functionality.

**Comment by roecla** [comment]
#8 already uses the date.
